<a href="https://colab.research.google.com/github/smtmn0/AminaS/blob/main/C%D3%A8%D0%964.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  NumPy және Машиналық Оқыту үшін Python Негіздері

**Тапсырма саны:** 10  

##  Нұсқаулық

Төмендегі 10 тапсырманың әрқайсысында `# КОДТЫ ОСЫНДА ЖАЗ` деген белгі бар. Сол жерге өз шешімінді жаз.


In [ ]:
# Қажетті кітапханаларды импорттау
import numpy as np
import math

# I Бөлім: NumPy Кітапханасымен Жұмыс

**NumPy** (Numerical Python) сандық есептеулерге арналған Python кітапханасы. Ол көп өлшемді массивтермен (ndarray) жұмыс істеуге, математикалық операциялар жүргізуге және деректерді өңдеуге мүмкіндік береді. Машиналық оқытуда NumPy матрицалық есептеулер мен деректер алдын ала өңдеуінің негізі болып табылады.

> **Тапсырмалар 1–5:** NumPy массивтерін құру, индекстеу, операциялар және статистика.

## Тапсырма 1: NumPy Массивін Құру және Негізгі Сипаттамалар

**Мақсат:** NumPy массивін қолмен жасау және оның қасиеттерін зерттеу.

**Шарт:**

1. `[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]` мәндерінен тұратын NumPy массивін жаса.
2. Массивтің мынадай сипаттамаларын экранға шығар:
   - Өлшемі (`shape`)
   - Деректер типі (`dtype`)
   - Элементтер саны (`size`)
   - Өлшемдер саны (`ndim`)

**Күтілетін нәтиже үлгісі:**
```
Массив: [ 10  20  30  40  50  60  70  80  90 100]
Өлшемі: (10,)
Деректер типі: int64
Элементтер саны: 10
Өлшемдер саны: 1
```

In [4]:
# Тапсырма 1: NumPy массивін құру
import numpy as np
import math

array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(np.shape)
print(np.dtype)
print(np.size)
print(np.ndim)
# КОДТЫ ОСЫНДА ЖАЗ


<function shape at 0x7ed4b1d18040>
<class 'numpy.dtype'>
<function size at 0x7ed4b1d191c0>
<function ndim at 0x7ed4b1d19080>


## Тапсырма 2: Матрица Құру және Матрицалық Операциялар

**Мақсат:** 2D массив (матрица) жасау және негізгі матрицалық операцияларды орындау.

NumPy-да матрицалар 2 өлшемді ndarray ретінде сақталады. Машиналық оқытуда деректер жиыны көбінесе (n_samples × n_features) пішіндегі матрица түрінде ұсынылады. Матрицалық операциялар линейлі регрессия, нейрондық желілер және басқа алгоритмдердің негізін қалайды.

**Шарт:**

1. Мынадай 3×3 матрицаны жаса:
```
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```
2. Осы матрицаны **транспонирлей** (`.T`).
3. Матрицаны өзіне **матрицалық көбейт** (`np.dot` немесе `@`).
4. Нәтижелерді экранға шығар.

In [8]:
# Тапсырма 2: Матрица және матрицалық операциялар

# КОДТЫ ОСЫНДА ЖАЗ
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
transposed_matrix = matrix.T
matrix_product = matrix @ matrix

print(matrix)
print(transposed_matrix)
print( matrix_product)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


## Тапсырма 3: Индекстеу, Тілімдеу (Slicing) және Сүзгілеу

**Мақсат:** NumPy массивіндегі элементтерге индекс арқылы қол жеткізу және шарт бойынша сүзу.

NumPy-да Boolean маска — шартқа сай элементтерді таңдаудың тиімді тәсілі. Мысалы, деректерден аномалиялар немесе белгілі бір диапазондағы мәндерді жылдам алып тастауға болады. Бұл алдын ала өңдеу (preprocessing) кезеңінде жиі қолданылады.

**Шарт:**

1. 1-ден 20-ға дейінгі сандардан тұратын массив жаса (`np.arange`).
2. Массивтің **алғашқы 5** элементін шығар.
3. Массивтің **соңғы 5** элементін шығар.
4. Массивтің **жұп индекстегі** элементтерін шығар (0, 2, 4, ...).
5. Мәні **10-нан үлкен** элементтерді ғана шығар (Boolean индекстеу).

In [9]:
# Тапсырма 3: Индекстеу, тілімдеу және сүзгілеу

# КОДТЫ ОСЫНДА ЖАЗ
import numpy as np

arr = np.arange(1, 21)
first_five = arr[:5]
last_five = arr[-5:]
even_indices = arr[::2]
greater_than_10 = arr[arr > 10]

print("Толық массив:", arr)
print("Алғашқы 5 элемент:", first_five)
print("Соңғы 5 элемент:", last_five)
print("Жұп индекстегі элементтер:", even_indices)
print("10-нан үлкен элементтер:", greater_than_10)

Толық массив: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Алғашқы 5 элемент: [1 2 3 4 5]
Соңғы 5 элемент: [16 17 18 19 20]
Жұп индекстегі элементтер: [ 1  3  5  7  9 11 13 15 17 19]
10-нан үлкен элементтер: [11 12 13 14 15 16 17 18 19 20]


## Тапсырма 4: Статистикалық Функциялар

**Мақсат:** NumPy-дың кірістірілген статистикалық функцияларын пайдалану.

Деректерді зерттеудің (EDA) бірінші қадамы — негізгі статистикалық көрсеткіштерді есептеу. Орташа мән, медиана, стандартты ауытқу және персентильдер деректер таралуын түсінуге көмектеседі. NumPy бұл есептеулерді векторланған түрде өте жылдам орындайды.

**Шарт:**

`np.random.seed(42)` арқылы кездейсоқтықты бекіт, содан кейін 0-ден 100-ге дейінгі **50 кездейсоқ бүтін сан** жаса.

Келесі статистикалық көрсеткіштерді есепте және шығар:
- Минимум және максимум
- Орташа мән (mean)
- Медиана
- Стандартты ауытқу
- Дисперсия
- 25-ші және 75-ші персентильдер

In [11]:
# Тапсырма 4: Статистикалық функциялар
np.random.seed(42)  # Қайталануы үшін кездейсоқтықты бекіту

# КОДТЫ ОСЫНДА ЖАЗ
import numpy as np

np.random.seed(42)
data = np.random.randint(0, 101, 50)

minimum = np.min(data)
maximum = np.max(data)
mean_val = np.mean(data)
median_val = np.median(data)
std_dev = np.std(data)
variance = np.var(data)
p25 = np.percentile(data, 25)
p75 = np.percentile(data, 75)

print(f"Массив: {data}\n")
print(f"Минимум: {minimum}, Максимум: {maximum}")
print(f"Орташа мән: {mean_val:.2f}")
print(f"Медиана: {median_val}")
print(f"Стандартты ауытқу: {std_dev:.2f}")
print(f"Дисперсия: {variance:.2f}")
print(f"25-ші персентиль: {p25}")
print(f"75-ші персентиль: {p75}")

Массив: [ 51  92  14  71  60  20  82  86  74  74  87  99  23   2  21  52   1  87
  29  37   1  63  59  20  32  75  57  21  88  48  90  58  41  91  59  79
  14  61  61  46  61  50  54  63   2 100  50   6  20  72]

Минимум: 1, Максимум: 100
Орташа мән: 52.08
Медиана: 57.5
Стандартты ауытқу: 28.62
Дисперсия: 819.11
25-ші персентиль: 24.5
75-ші персентиль: 74.0


## Тапсырма 5: Пішінді Өзгерту (Reshape) және Хабарлау (Broadcasting)

**Мақсат:** Массив пішінін өзгерту және NumPy broadcasting механизмін түсіну.

Broadcasting  NumPy-дың әртүрлі пішіндегі массивтерге автоматты түрде арифметикалық операция қолдану мүмкіндігі. Reshape функциясы деректерді нейрондық желілерге немесе sklearn модельдеріне беру алдында жиі қолданылады.

**Шарт:**

1. 1-ден 12-ге дейінгі сандардан тұратын массив жаса (`np.arange`).
2. Оны **3×4 матрицаға** түрлендір (`reshape`).
3. Матрицаның **әр жолына** `[10, 20, 30, 40]` векторын қос (broadcasting).
4. Матрицаның **әр бағанын** `[[1], [2], [3]]` бағандық векторына көбейт (broadcasting).
5. Нәтижелерді шығар.

In [ ]:
# Тапсырма 5: Reshape және Broadcasting

# КОДТЫ ОСЫНДА ЖАЗ


# II Бөлім: Машиналық Оқыту үшін Python Негіздері

Python-ның функциялары мен кластары машиналық оқыту жүйелерін модульдік және қайта пайдалануға болатын түрде құруға мүмкіндік береді. ML pipeline-дарын, деректерді өңдеу логикасын және модель архитектурасын таза кодпен ұйымдастыру үшін OOP принциптері өте маңызды. scikit-learn кітапханасының өзі де осындай кластық құрылымға негізделген.

> **Тапсырмалар 6–10:** Функциялар, декораторлар, кластар және ML компоненттерін модельдеу.

## Тапсырма 6: ML Алдын Ала Өңдеу Функциялары

**Мақсат:** Деректерді нормализациялайтын және стандарттайтын функциялар жазу.

Нормализация мен стандарттау — ML алгоритмдерінің дұрыс жұмыс істеуі үшін маңызды алдын ала өңдеу қадамдары. Min-Max нормализациясы мәндерді [0, 1] диапазонына, Z-score стандарттауы орташа мәнді 0, стандартты ауытқуды 1 етіп түрлендіреді. Бұл SVM, KNN, нейрондық желі сияқты алгоритмдер үшін өте маңызды.

**Шарт:**

Екі функция жаз:

**`min_max_normalize(arr)`** — Min-Max нормализациясы:
$$x_{norm} = \frac{x - x_{min}}{x_{max} - x_{min}}$$

**`z_score_standardize(arr)`** — Z-score стандарттауы:
$$x_{std} = \frac{x - \mu}{\sigma}$$

Екі функцияны да `[2, 4, 4, 4, 5, 5, 7, 9]` массивіне қолдан және нәтижені шығар.

In [12]:
# Тапсырма 6: Нормализация және стандарттау функциялары

# КОДТЫ ОСЫНДА ЖАЗ

import numpy as np

arr = np.arange(1, 13)
matrix = arr.reshape(3, 4)

row_vector = np.array([10, 20, 30, 40])
added_matrix = matrix + row_vector

col_vector = np.array([[1], [2], [3]])
multiplied_matrix = matrix * col_vector

print("Бастапқы:", matrix)
print("\nВекторды жолдарға қосқаннан кейін:\n", added_matrix)
print("\nБағандық векторға көбейткеннен кейін:\n", multiplied_matrix)

Бастапқы: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Векторды жолдарға қосқаннан кейін:
 [[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]

Бағандық векторға көбейткеннен кейін:
 [[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]


## Тапсырма 7: Рекурсия және Lambda Функциялар

**Мақсат:** Рекурсивті функция және lambda өрнектерін ML контекстінде қолдану.

Lambda функциялар — атаусыз шағын функциялар, ML-де деректерді трансформациялау үшін `map()`, `filter()`, `sorted()` функцияларымен жиі қолданылады. Рекурсия болса күрделі алгоритмдерді (мысалы, шешім ағашының тереңдігін есептеу) элегантты жазуға мүмкіндік береді.

**Шарт:**

1. **Рекурсивті функция:** `factorial(n)` — n! санын рекурсия арқылы есепте.
2. **Lambda:** `[0.1, 0.5, 0.9, 1.5, -0.3, 2.0]` тізімінен тек `[0, 1]` диапазонындағы мәндерді `filter` + `lambda` арқылы алып шығар.
3. **Lambda + map:** `[-2, -1, 0, 1, 2]` тізіміндегі әр элементке ReLU активация функциясын `map` + `lambda` арқылы қолдан.

> ReLU(x) = max(0, x)

In [13]:
# Тапсырма 7: Рекурсия және Lambda функциялар

# КОДТЫ ОСЫНДА ЖАЗ

def factorial(n):
    if n == 0 or n == 1:
        return 1
    return n * factorial(n - 1)

numbers = [0.1, 0.5, 0.9, 1.5, -0.3, 2.0]

filtered = list(filter(lambda x: 0 <= x <= 1, numbers))

print(filtered)

values = [-2, -1, 0, 1, 2]

relu_values = list(map(lambda x: max(0, x), values))

print( relu_values)

[0.1, 0.5, 0.9]
[0, 0, 0, 1, 2]


## Тапсырма 8: Кластар — ML Метрикаларын Есептеуші

**Мақсат:** OOP принциптерін пайдаланып, классификация метрикаларын есептейтін класс жазу.

Машиналық оқытуда модель сапасын бағалау үшін Accuracy, Precision, Recall, F1-score метрикалары қолданылады. Оларды бір класс ішінде топтастыру кодтың модульдігін арттырады және sklearn-дің `classification_report` функциясына ұқсас нәтиже береді.

**Шарт:**

`ClassificationMetrics` атты класс жаз. Конструктор `y_true` (нақты мәндер) және `y_pred` (болжамдар) параметрлерін қабылдасын.

Класта мынадай әдістер болуы керек:
- `accuracy()` — дұрыс болжамдар үлесі
- `precision()` — дәлдік: TP / (TP + FP)
- `recall()` — толықтық: TP / (TP + FN)
- `f1_score()` — F1: 2 × (precision × recall) / (precision + recall)
- `report()` — барлық метрикаларды форматталған түрде шығарады

Тест деректері:
```python
y_true = [1, 0, 1, 1, 0, 1, 0, 0, 1, 0]
y_pred = [1, 0, 1, 0, 0, 1, 1, 0, 1, 0]
```

In [15]:
# Тапсырма 8: ClassificationMetrics класы

# Тест деректері
y_true = [1, 0, 1, 1, 0, 1, 0, 0, 1, 0]  # Нақты белгілер
y_pred = [1, 0, 1, 0, 0, 1, 1, 0, 1, 0]  # Болжамдар

# КОДТЫ ОСЫНДА ЖАЗ
class ClassificationMetrics:
    def __init__(self, y_true, y_pred):
        self.y_true = y_true
        self.y_pred = y_pred
        self._calculate_base_counts()

    def _calculate_base_counts(self):
        self.tp = sum(1 for yt, yp in zip(self.y_true, self.y_pred) if yt == 1 and yp == 1)
        self.fp = sum(1 for yt, yp in zip(self.y_true, self.y_pred) if yt == 0 and yp == 1)
        self.fn = sum(1 for yt, yp in zip(self.y_true, self.y_pred) if yt == 1 and yp == 0)
        self.tn = sum(1 for yt, yp in zip(self.y_true, self.y_pred) if yt == 0 and yp == 0)

    def accuracy(self):
        return (self.tp + self.tn) / len(self.y_true)

    def precision(self):
        return self.tp / (self.tp + self.fp) if (self.tp + self.fp) > 0 else 0

    def recall(self):
        return self.tp / (self.tp + self.fn) if (self.tp + self.fn) > 0 else 0

    def f1_score(self):
        p = self.precision()
        r = self.recall()
        return 2 * (p * r) / (p + r) if (p + r) > 0 else 0

    def report(self):
        print("--- Classification Report ---")
        print(f"Accuracy:  {self.accuracy():.2f}")
        print(f"Precision: {self.precision():.2f}")
        print(f"Recall:    {self.recall():.2f}")
        print(f"F1-score:  {self.f1_score():.2f}")
        print("-" * 29)
metrics = ClassificationMetrics(y_true, y_pred)
metrics.report()


--- Classification Report ---
Accuracy:  0.80
Precision: 0.80
Recall:    0.80
F1-score:  0.80
-----------------------------


## Тапсырма 9: Мұрагерлік (Inheritance) — ML Модель Иерархиясы

**Мақсат:** Python-да кластар иерархиясын (мұрагерлік) пайдаланып ML модельдерін модельдеу.

Мұрагерлік (inheritance) — OOP-тың негізгі принципі. scikit-learn барлық модельдерін `BaseEstimator` базалық класынан туындатады, бұл `fit()`, `predict()`, `score()` сияқты ортақ интерфейсті қамтамасыз етеді. Осы паттернді түсіну ML кітапханаларының архитектурасын жобалауға негіз береді.

**Шарт:**

1. **`BaseModel`** — базалық класс:
   - `__init__(self, model_name)` — модель атын сақтайды
   - `fit(X, y)` — `NotImplementedError` шығарады (абстрактілі)
   - `predict(X)` — `NotImplementedError` шығарады (абстрактілі)
   - `describe()` — модель туралы ақпаратты шығарады

2. **`LinearRegressionModel(BaseModel)`** — туынды класс:
   - `fit(X, y)` — `np.linalg.lstsq` арқылы коэффициенттерді табады
   - `predict(X)` — `X @ weights` арқылы болжайды
   - `describe()` — базалық сипаттаманы + коэффициенттерді шығарады

3. Тест деректерінде `fit` → `predict` → `describe` тізбегін шақыр.

In [16]:
# Тапсырма 9: Мұрагерлік — ML Модель Иерархиясы

# Тест деректері
np.random.seed(0)
X_train = np.column_stack([np.ones(20), np.random.randn(20)])  # Бір фичалы деректер
y_train = 3 * X_train[:, 1] + 5 + np.random.randn(20) * 0.5  # y = 3x + 5 + шу

# КОДТЫ ОСЫНДА ЖАЗ
import numpy as np

class BaseModel:
    def __init__(self, model_name):
        self.model_name = model_name
        self.is_fitted = False

    def fit(self, X, y):
        raise NotImplementedError("fit әдісі туынды класста іске асырылуы керек")

    def predict(self, X):
        raise NotImplementedError("predict әдісі туынды класста іске асырылуы керек")

    def describe(self):
        print(f"Модель: {self.model_name}")
        if not self.is_fitted:
            print("  (әлі оқытылмаған)")
        else:
            print("  (оқытылған модель)")


class LinearRegressionModel(BaseModel):
    def __init__(self):
        super().__init__("Жай сызықты регрессия (numpy)")
        self.weights = None

    def fit(self, X, y):
        self.weights, _, _, _ = np.linalg.lstsq(X, y, rcond=None)
        self.is_fitted = True
        return self

    def predict(self, X):
        if not self.is_fitted:
            raise ValueError("Модель әлі fit әдісімен оқытылмаған!")
        return X @ self.weights

    def describe(self):
        super().describe()
        if self.is_fitted:
            print(f"  w0 (intercept) = {self.weights[0]:.4f}")
            print(f"  w1 (slope)     = {self.weights[1]:.4f}")


model = LinearRegressionModel()

print("Модельді оқыту алдында:")
model.describe()
print("-" * 50)

model.fit(X_train, y_train)

print("\nОқытудан кейін:")
model.describe()
print("-" * 50)

print("\nАлғашқы 5 нақты және болжамды мәндер:")
predictions = model.predict(X_train[:5])
for i in range(5):
    print(f"  Нақты: {y_train[i]:6.3f}    Болжам: {predictions[i]:6.3f}")


Модельді оқыту алдында:
Модель: Жай сызықты регрессия (numpy)
  (әлі оқытылмаған)
--------------------------------------------------

Оқытудан кейін:
Модель: Жай сызықты регрессия (numpy)
  (оқытылған модель)
  w0 (intercept) = 4.9931
  w1 (slope)     = 3.0610
--------------------------------------------------

Алғашқы 5 нақты және болжамды мәндер:
  Нақты:  9.016    Болжам: 10.393
  Нақты:  6.527    Болжам:  6.218
  Нақты:  8.368    Болжам:  7.989
  Нақты: 11.352    Болжам: 11.853
  Нақты: 11.738    Болжам: 10.710


## !КҮРДЕЛІ
##Тапсырма 10: Толыққанды ML Pipeline Класы

**Мақсат:** Нақты ML жүйесін модельдейтін толыққанды Pipeline класын жазу.

ML Pipeline  деректерді алдын ала өңдеу, модельді оқыту және бағалау қадамдарын автоматты реттілікпен орындайтын құрылым. sklearn-дің `Pipeline` класы осындай принципте жұмыс істейді. Мұны өз бетімен жүзеге асыру бүкіл ML жұмыс ағынын терең түсінуге мүмкіндік береді.

**Шарт:**

`MLPipeline` класы жаз, ол мынадай кезең-кезеңді іске асырсын:

1. **`load_data(X, y)`** — деректерді сақтайды
2. **`train_test_split(test_ratio=0.2)`** — деректерді оқыту/тест жиынтықтарына бөледі
3. **`normalize()`** — оқыту жиынтығы бойынша Min-Max нормализациясын жасайды (тест жиынына да қолданады)
4. **`train()`** — `np.linalg.lstsq` арқылы линейлі регрессия оқытады
5. **`evaluate()`** — MSE және R² метрикаларын есептейді
6. **`run()`** — барлық қадамдарды дұрыс ретпен шақырады

Тест деректерінде толық `run()` жүргіз және нәтижені шығар.

> **Кеңес:** R² = 1 - SS_res / SS_tot, мұндағы SS_res = Σ(y - ŷ)², SS_tot = Σ(y - ȳ)²

In [17]:
import numpy as np

class MLPipeline:
    def __init__(self):
        self.X = None
        self.y = None
        self.X_train = None
        self.X_test = None
        self.y_train = None
        self.y_test = None
        self.X_train_norm = None
        self.X_test_norm = None
        self.weights = None
        self.min_val = None
        self.max_val = None

    def load_data(self, X, y):
        self.X = X.copy()
        self.y = y.copy()

    def train_test_split(self, test_ratio=0.2):
        n = len(self.y)
        test_size = int(n * test_ratio)
        indices = np.arange(n)
        np.random.shuffle(indices)

        test_idx = indices[:test_size]
        train_idx = indices[test_size:]

        self.X_train = self.X[train_idx]
        self.X_test  = self.X[test_idx]
        self.y_train = self.y[train_idx]
        self.y_test  = self.y[test_idx]

    def normalize(self):
        self.min_val = self.X_train.min(axis=0)
        self.max_val = self.X_train.max(axis=0)
        denom = self.max_val - self.min_val
        denom[denom == 0] = 1

        self.X_train_norm = (self.X_train - self.min_val) / denom
        self.X_test_norm  = (self.X_test  - self.min_val) / denom

        self.X_train_norm = np.column_stack([np.ones(len(self.X_train_norm)), self.X_train_norm])
        self.X_test_norm  = np.column_stack([np.ones(len(self.X_test_norm)), self.X_test_norm])

    def train(self):
        self.weights, _, _, _ = np.linalg.lstsq(self.X_train_norm, self.y_train, rcond=None)

    def evaluate(self):
        y_pred = self.X_test_norm @ self.weights
        mse = np.mean((self.y_test - y_pred) ** 2)

        y_mean = np.mean(self.y_test)
        ss_tot = np.sum((self.y_test - y_mean) ** 2)
        ss_res = np.sum((self.y_test - y_pred) ** 2)
        r2 = 1 - (ss_res / ss_tot) if ss_tot != 0 else 0

        return mse, r2

    def run(self):
        print("Деректерді бөлу...")
        self.train_test_split()

        print("Нормализация...")
        self.normalize()

        print("Модель оқыту...")
        self.train()

        print("Нәтижелерді есептеу...")
        mse, r2 = self.evaluate()

        print("\n" + "="*50)
        print(f"Test жиыны ({len(self.y_test)} үлгі):")
        print(f"  MSE:  {mse:.6f}")
        print(f"  R²:   {r2:.6f}")
        print("="*50)

        print("\nКоэффициенттер:")
        for i, w in enumerate(self.weights):
            print(f"  w{i}: {w:.6f}")


np.random.seed(42)
n_samples = 100
X_data = np.random.randn(n_samples, 3)
y_data = 2 * X_data[:, 0] - 1.5 * X_data[:, 1] + 0.5 * X_data[:, 2] + np.random.randn(n_samples) * 0.3

pipe = MLPipeline()
pipe.load_data(X_data, y_data)
pipe.run()

Деректерді бөлу...
Нормализация...
Модель оқыту...
Нәтижелерді есептеу...

Test жиыны (20 үлгі):
  MSE:  0.078371
  R²:   0.983108

Коэффициенттер:
  w0: 0.086684
  w1: 7.543893
  w2: -8.279223
  w3: 2.201894


# Қорытынды және Өзін-өзі Бағалау

(міндетті емес) Барлық тапсырмаларды орындап болған соң, төмендегі кестені толтыр:

| Тапсырма | Тақырып | Орындалды? | Қиындықтар |
|:--------:|---------|:----------:|------------|
| 1 | NumPy массиві және сипаттамалар | ☐ | |
| 2 | Матрица және матрицалық операциялар | ☐ | |
| 3 | Индекстеу және сүзгілеу | ☐ | |
| 4 | Статистикалық функциялар | ☐ | |
| 5 | Reshape және Broadcasting | ☐ | |
| 6 | Нормализация функциялары | ☐ | |
| 7 | Рекурсия және Lambda | ☐ | |
| 8 | ClassificationMetrics класы | ☐ | |
| 9 | Мұрагерлік — ML иерархиясы | ☐ | |
| 10 | ML Pipeline класы | ☐ | |

---

**Пікір (міндетті емес):**

_Осы үй жұмысын орындау барысында не үйрендің? Қандай тапсырма ең қызықты болды?_


---